### ISSUE TITLE
Mistake of parse Catalist 6500 IOS 12.2,12.4 config

### ISSUE THREAD

**Issue by Breskii** [mpenning/ciscoconfparse#88] opened 2017-09-06 05:50 UTC
The bug was found during parsing "show run" output of command of Catalist 6500, IOS 12.2,12.4. Address-family parameters not have extra spaces at the beginning of the line. ciscoconfparse does not show any child under address-family.
Example:
router bgp 65010
 address-family ipv4
 neighbor RR activate
 ...
 maximum-paths 4
 no auto-summary
 no synchronization
 exit-address-family
 !
!

**Comment by mpenning** [comment] 2017-10-16 17:30
This is a duplicate of Github Issue #72

**Closed by mpenning** 2017-10-16 17:30 UTC
Labels: duplicate
