### ISSUE TITLE
ImportError: cannot import name 'CiscoConfParse'

### ISSUE THREAD

**Issue by Suterusu1337** [mpenning/ciscoconfparse#98] opened 2018-02-12 04:55 UTC
I am unable to get ciscoconfparse to load from the interactive interpreter on Python 3.6.3

```
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse import CiscoConfParse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CiscoConfParse'
```
ciscoconfparse (1.3.2)

**Comment by mbrar** [comment] 2018-02-12 22:23
Experiencing same issues. __init__.py brings in everything from ciscoconfparse.py. It works if you do the import at the package dir ex) /usr/local/lib/python3.5/dist-pacakges/ciscoconfparse. So packaging is causing some trouble with the PYTHONPATH it seems.

**Comment by Suterusu1337** [comment] 2018-02-13 00:08
@mbrar do you have a work around or something I can change in order to get it to function (without having to run from a specific directory)?

**Comment by Suterusu1337** [comment] 2018-02-13 04:28
The import path seems very wrong, like too many levels nested.  This is the only way I've had the import not fail, but then the scripts cannot find other modules located in the same directory.
```
from ciscoconfparse.ciscoconfparse import CiscoConfParse

parse = CiscoConfParse(['!'])
```
--------------
```
/home/brice/.virtualenvs/net/bin/python /home/brice/projects/py/net/test.py
Traceback (most recent call last):
  File "/home/brice/projects/py/net/test.py", line 1, in <module>
    from ciscoconfparse.ciscoconfparse import CiscoConfParse
  File "/home/brice/.virtualenvs/net/lib/python3.6/site-packages/ciscoconfparse/ciscoconfparse.py", line 11, in <module>
    from models_cisco import IOSHostnameLine, IOSRouteLine, IOSIntfLine
ModuleNotFoundError: No module named 'models_cisco'

Process finished with exit code 1
```

**Comment by mpenning** [comment] 2018-02-13 10:41
I'm not sure why this is happening yet, but if you roll back to ciscoconfparse==1.3.1 then it still works... I'm pretty busy with my $dayjob this week, so maybe I can put some time into fixing this next week.

There were mostly trivial changes between 1.3.1 to 1.3.2... you're not going to miss much by rolling back.

Explicitly, you should do this...
``pip3 uninstall ciscoconfparse; pip3 install ciscoconfparse==1.3.1``

**Comment by mpenning** [comment] 2018-02-13 11:06
I'm going through cycles of either breaking python2 or python3 every time I change something... version 1.3.1 is safest at this time.  

For Python3: ``pip3 install ciscoconfparse==1.3.1``
For Python2: ``pip install ciscoconfparse==1.3.1``

**Comment by johnarnold** [comment] 2018-02-13 20:36
@mpenning  I found 1.3.1 still broke us, we went back to 1.2.55

**Comment by sinontaylor** [comment] 2018-02-14 06:04
1.3.1 worked for me. thanks.

**Comment by mpenning** [comment] 2018-02-14 16:20
@johnarnold this is very interesting; @sinontaylor can use 1.3.1 and you can't (i.e. you rolled back to 1.2.55).  Could both of you quantify your environments?

* What platform (OS, including linux distro / version if linux) are you running ciscoconfparse on?
* What version of python are you running?  Did you custom-build your python from scratch, or are you running something provided by your OS?
* How did you install ciscoconfparse?  Did you use pip, git clone / setup.py or something else?
* Please include the output of ``pip freeze`` or ``pip3 freeze``, as appropriate.

Knowing this may help me figure out what is breaking the latest releases of ciscoconfparse (and perhaps I can write a unit test to capture this problem... although TravisCI [cannot test Windows](https://github.com/travis-ci/travis-ci/issues/216#issuecomment-124138138))

**Comment by sinontaylor** [comment] 2018-02-15 01:58
Hi,

- I'm running "Oracle Linux Server release 6.3"
- Python 3.6.4 (installed using make)
- python3 -m pip install ciscoconfparse==1.3.1


asn1crypto==0.24.0
bcrypt==3.1.4
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
ciscoconfparse==1.3.1
colorama==0.3.9
cryptography==2.1.4
dnspython==1.15.0
dnspython3==1.15.0
idna==2.6
ipaddr==2.2.0
ipaddress==1.0.19
ldap==1.0.2
ldap3==2.4.1
lxml==4.1.1
ncclient==0.5.3
netmiko==2.0.2
pan-python==0.12.0
pandevice==0.5.3
paramiko==2.4.0
pexpect==4.4.0
pprint==0.1
ptyprocess==0.5.2
pyasn1==0.4.2
pycparser==2.18
PyMySQL==0.8.0
PyNaCl==1.2.1
pyserial==3.4
PyYAML==3.12
requests==2.18.4
scp==0.10.2
six==1.11.0
textfsm==0.3.2
urllib3==1.22
virtualenv==15.1.0
xmltodict==0.11.0

Cheers, Simon

**Comment by mpenning** [comment] 2018-02-16 15:46
@johnarnold, when you get time please update the issue with answers to my questions above...

**Comment by mpenning** [comment] 2018-03-03 14:54
In the absence of any other input, I'm closing this after changing bdist_wheel back to universal=0 in `setup.cfg`.  This seems to fix both python2 and python3 in linux.

**Closed by mpenning** 2018-03-03 14:54 UTC

**Comment by roganartu** [comment] 2019-05-08 03:15
This still happens for me when `ciscoconfparse` is installed as a dep for napalm.

Python version: 3.6.5
ciscoconfparse version: 1.3.36

I tried downgrading to 1.3.1 as suggested above, but that didn't resolve the problem.

I did some digging through the source and I'm fairly sure this is an absolute vs relative import problem, where the internal imports are failing to resolve to the local files within the module. This theory is supported by the fact that if you instead import `ciscoconfparse.ciscoconfparse import CiscoConfParse` the error changes to `ModuleNotFoundError: No module named 'models_cisco'`. Editing my locally installed version and prepending the relative import dot to all internal imports across all files fixes this.

I'm not sure why this seems to manifest only for some users running py3 (aside from the fact that implicit relative imports were removed in py3), but I suspect it's got something to do with installing from sdist vs bdist and the `2to3=True` in `setup.py`. In any case, the proper fix is easy and compatible with both py2 and py3; I will submit a PR soon.

**Comment by roganartu** [comment] 2019-05-08 14:50
> @roganartu said:
> 
> > this is an absolute vs relative import problem
> 
> Please be explicit about where you see relative imports that break in your installation. When I completely disable relative imports with `from __future__ import absolute_import` in `ciscoconfparse.py`, I do not get errors.

The one that specifically causes the exception in the title of this issue is actually the import in `__init__.py`
```
from ciscoconfparse import *
```
This is meant to expose everything inside `ciscoconfparse.py` at the module level (and does in py2), but because there's no implied relative imports in py3 it's effectively a no-op. Implied relative imports are used in almost every file in this package though.

How did you check for errors after adding `from __future__ import absolute_import`? `make test` fails to replicate the issue because all the test files explicitly add `../ciscoconfparse` to `sys.path` which works around the bug.

Steps to replicate with py3
```
$ git clone https://github.com/mpenning/ciscoconfparse.git
...
$ cd ciscoconfparse
$ python3.6 -m virtualenv -p $(which python3.6) env
...
$ . env/bin/activate
$ pip install -e ./              
Obtaining file:///home/tl/src/ciscoconfparse
Collecting colorama (from ciscoconfparse==1.3.36)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting passlib (from ciscoconfparse==1.3.36)
  Downloading https://files.pythonhosted.org/packages/ee/a7/d6d238d927df355d4e4e000670342ca4705a72f0bf694027cf67d9bcf5af/passlib-1.7.1-py2.py3-none-any.whl (498kB)
     |████████████████████████████████| 501kB 14.6MB/s 
Collecting dnspython (from ciscoconfparse==1.3.36)
  Using cached https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl
Installing collected packages: colorama, passlib, dnspython, ciscoconfparse
  Running setup.py develop for ciscoconfparse
Successfully installed ciscoconfparse colorama-0.4.1 dnspython-1.16.0 passlib-1.7.1
$ python
Python 3.6.5 (default, Nov 19 2018, 18:02:26) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse import CiscoConfParse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CiscoConfParse'
```

Steps to replicate with py2:
```
$ rm -rf env
$ python2.7 -m virtualenv -p $(which python2.7) env
...
$ . env/bin/activate
$ pip install -e ./
Obtaining file:///home/tl/src/ciscoconfparse
Collecting colorama (from ciscoconfparse==1.3.36)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting passlib (from ciscoconfparse==1.3.36)
  Downloading https://files.pythonhosted.org/packages/ee/a7/d6d238d927df355d4e4e000670342ca4705a72f0bf694027cf67d9bcf5af/passlib-1.7.1-py2.py3-none-any.whl (498kB)
    100% |████████████████████████████████| 501kB 2.2MB/s 
Collecting dnspython (from ciscoconfparse==1.3.36)
  Downloading https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 194kB 4.1MB/s 
Collecting ipaddr>=2.1.11 (from ciscoconfparse==1.3.36)
  Downloading https://files.pythonhosted.org/packages/9d/a7/1b39a16cb90dfe491f57e1cab3103a15d4e8dd9a150872744f531b1106c1/ipaddr-2.2.0.tar.gz
Building wheels for collected packages: ipaddr
  Running setup.py bdist_wheel for ipaddr ... done
  Stored in directory: /home/tl/.cache/pip/wheels/c8/46/0b/5220490c49f714459a27e1eaafe3eef4c7a5e9bb4e9baf10ca
Successfully built ipaddr
Installing collected packages: colorama, passlib, dnspython, ipaddr, ciscoconfparse
  Running setup.py develop for ciscoconfparse
Successfully installed ciscoconfparse colorama-0.4.1 dnspython-1.16.0 ipaddr-2.2.0 passlib-1.7.1
$ python
Python 2.7.13 (default, Dec 19 2017, 15:27:49) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse import CiscoConfParse
>>> 
$ (echo "from __future__ import absolute_import" && cat ciscoconfparse/ciscoconfparse.py) > tmpfile && mv tmpfile ciscoconfparse/ciscoconfparse.py
$ python                                           
Python 2.7.13 (default, Dec 19 2017, 15:27:49) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse import CiscoConfParse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ciscoconfparse/__init__.py", line 1, in <module>
    from ciscoconfparse import *
  File "ciscoconfparse/ciscoconfparse.py", line 18, in <module>
    from models_cisco import IOSHostnameLine, IOSRouteLine, IOSIntfLine
ImportError: No module named models_cisco
>>>
```
Note that the Py2 replication makes it past `from ciscoconfparse import *` where Py3 fails. This is because Py2 is resolving `ciscoconfparse` to `ciscoconfparse.py` while Py3 isn't. It then falls over on the first implied-relative import in `ciscoconfparse.py` because implied-relative imports were disabled in that file.

Prepending a `.` to all the relative imports to make them explicitly relative resolves the problem for Py3 without breaking Py2 compatibility, eg:
```
from .ciscoconfparse import *
```

> 
> Before we go stampeding off to submit a PR, please consider adding some details about:
> 
> What operating system are you running?

Debian Stretch.

> How did you install python?

System `python3.6` inside a venv. Installed globally via standard deb package.
 
> How did you install ciscoconfparse?

via pip inside the venv

**Comment by mpenning** [comment] 2019-05-08 15:03
@roganartu said:
> via pip inside the venv

Please do not use pip to install under python3.  You must use pip3.

I can't be sure whether that's your problem, but you should at least:
- uninstall ciscoconfparse installed via pip
- install ciscoconfparse with pip3

While it's possible that your concern in `__init__.py` is valid; I can't believe the literally thousands of people installing this project monthly (before you did) would not have already stumbled on this problem.

Nevertheless I will consider changing `__init__.py` after I do some more investigation

**Comment by roganartu** [comment] 2019-05-08 15:43
> @roganartu said:
> 
> > via pip inside the venv
> 
> Please do not use pip to install under python3. You must use pip3.
> 
> I can't be sure whether that's your problem, but you should at least:
> 
>     * uninstall ciscoconfparse installed via pip
> 
>     * install ciscoconfparse with pip3

This is not necessary inside a venv. In a py3 venv `pip` and `pip3` are identical, one is just a symlink to the other.
```
$ python3.6 -m virtualenv -p $(which python3.6) env
...
$ which pip
/home/tl/src/ciscoconfparse/env/bin/pip
$ pip --version
pip 19.1.1 from /home/tl/src/ciscoconfparse/env/lib/python3.6/site-packages/pip (python 3.6)
$ pip3 --version
pip 19.1.1 from /home/tl/src/ciscoconfparse/env/lib/python3.6/site-packages/pip (python 3.6)
```

> While it's possible that your concern in `__init__.py` is valid; I can't believe the literally thousands of people installing this project monthly (before you did) would not have already stumbled on this problem.
> 
> Nevertheless I will consider changing `__init__.py` after I do some more investigation

It's not just `__init__.py`, it's every implicit relative import in the whole package. If you change just `__init__.py` then the exception will just move to the next relative import encountered.

I'm a little surprised this complaint isn't more common, but it doesn't seem unrealistic given you're using the `use_2to3` setuptools flag. From the docs (emphasis mine):

> Setuptools provides a facility to invoke 2to3 on the code as a part of the build process, by setting the keyword parameter use_2to3 to True, but _the Setuptools project strongly recommends instead developing a unified codebase using six, future, or another compatibility library._

My understanding is that setuptools only runs `2to3` from this flag when building bdists for upload to pypi, so any versions of `ciscoconfparse` that weren't explicitly built for py3 are going to be installed from source and hence not be py3 compatible. You can verify this by installing `ciscoconfparse==1.3.26` in a fresh py3 venv and it will work fine because it has a python3 bdist available (seems you've only explicitly built and uploaded versions for py3 a few times):
```
$ curl -s https://pypi.org/simple/ciscoconfparse/ | grep py3
    <a href="https://files.pythonhosted.org/packages/7a/e6/184c7ed00fb33eecf65a0a4b24a9d3b505786dccdaf84eb5f5174b12731d/ciscoconfparse-1.3.14-py3-none-any.whl#sha256=3e19a0f54a40e67c4da8a0282cd4de3e880d02cc50224f98b4d3e475d527b04e">ciscoconfparse-1.3.14-py3-none-any.whl</a><br/>
    <a href="https://files.pythonhosted.org/packages/2c/60/690b3a3c6272ffd80aecb9af1c7c1fb67ffdc7738fed1ba917a2aef7fc93/ciscoconfparse-1.3.15-py3-none-any.whl#sha256=38c3720a0798f98ccc5f039ba57545b75a9e18ff8082c985420a5204f496ffb8">ciscoconfparse-1.3.15-py3-none-any.whl</a><br/>
    <a href="https://files.pythonhosted.org/packages/16/fe/6392bfe65d889a623cc118032138f1799c52642df741ae6c6ccad0206d82/ciscoconfparse-1.3.26-py3-none-any.whl#sha256=7a8fd26e7126d4c37ddfdd11def4b88ebb78ed8fa75b64e455934e2c0434cbde">ciscoconfparse-1.3.26-py3-none-any.whl</a><br/>
    <a href="https://files.pythonhosted.org/packages/63/f4/89b2ee174c065a0bd99ff5ef826db3f0495c96a7400572b6bcee6c0da6fd/ciscoconfparse-1.3.27-py2.py3-none-any.whl#sha256=18370cb3f6c265e829b3f49a3d741bc57f9780a0c8a8c8b8a2ecffb87a2f817c">ciscoconfparse-1.3.27-py2.py3-none-any.whl</a><br/>
$ python3.6 -m virtualenv -p $(which python3.6) env
...
$ . env/bin/activate
$ pip install ciscoconfparse==1.3.26
Collecting ciscoconfparse==1.3.26
  Downloading https://files.pythonhosted.org/packages/16/fe/6392bfe65d889a623cc118032138f1799c52642df741ae6c6ccad0206d82/ciscoconfparse-1.3.26-py3-none-any.whl (88kB)
     |████████████████████████████████| 92kB 7.0MB/s 
Collecting colorama (from ciscoconfparse==1.3.26)
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting passlib (from ciscoconfparse==1.3.26)
  Using cached https://files.pythonhosted.org/packages/ee/a7/d6d238d927df355d4e4e000670342ca4705a72f0bf694027cf67d9bcf5af/passlib-1.7.1-py2.py3-none-any.whl
Collecting dnspython (from ciscoconfparse==1.3.26)
  Using cached https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl
Installing collected packages: colorama, passlib, dnspython, ciscoconfparse
Successfully installed ciscoconfparse-1.3.26 colorama-0.4.1 dnspython-1.16.0 passlib-1.7.1
$ python
Python 3.6.5 (default, Nov 19 2018, 18:02:26) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse import CiscoConfParse
>>> 
```

One of the things that `2to3` fixes is implied relative imports:
https://docs.python.org/2/library/2to3.html#2to3fixer-import

**Comment by mpenning** [comment] 2019-05-08 20:22
> @roganartu said:
> One of the things that `2to3` fixes is implied relative imports:
> https://docs.python.org/2/library/2to3.html#2to3fixer-import

Except you're reproducing this problem above by doing a git clone of ciscoconfparse's repo.  As such, 2to3 seems to be a red-herring: 

> @roganartu said:
> Steps to replicate with py3
> 
> ```
> $ git clone https://github.com/mpenning/ciscoconfparse.git
> ...
> $ cd ciscoconfparse
> $ python3.6 -m virtualenv -p $(which python3.6) env
> ...
> $ . env/bin/activate
> $ pip install -e ./              
> Obtaining file:///home/tl/src/ciscoconfparse
> Collecting colorama (from ciscoconfparse==1.3.36)
>   Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
> Collecting passlib (from ciscoconfparse==1.3.36)
>   Downloading https://files.pythonhosted.org/packages/ee/a7/d6d238d927df355d4e4e000670342ca4705a72f0bf694027cf67d9bcf5af/passlib-1.7.1-py2.py3-none-any.whl (498kB)
>      |████████████████████████████████| 501kB 14.6MB/s 
> Collecting dnspython (from ciscoconfparse==1.3.36)
>   Using cached https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl
> Installing collected packages: colorama, passlib, dnspython, ciscoconfparse
>   Running setup.py develop for ciscoconfparse
> Successfully installed ciscoconfparse colorama-0.4.1 dnspython-1.16.0 passlib-1.7.1
> $ python
> Python 3.6.5 (default, Nov 19 2018, 18:02:26) 
> [GCC 6.3.0 20170516] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from ciscoconfparse import CiscoConfParse
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'CiscoConfParse'
> ```
> 

Please don't submit a PR at this point.  I am not confident we know what is causing your problem.

**Comment by roganartu** [comment] 2019-05-08 23:54
> > @roganartu said:
> > One of the things that `2to3` fixes is implied relative imports:
> > https://docs.python.org/2/library/2to3.html#2to3fixer-import
> 
> Except you're reproducing this problem above by doing a git clone of ciscoconfparse's repo. As such, 2to3 seems to be a red-herring:

You seem to have misunderstood what I meant by this. I'm not claiming `use_2to3` is the cause of the problem, I'm claiming it's the reason this is not immediately broken for _everyone_ running py3. Anyone who installs one of the few py3 bdists available on pypi will not experience this issue because the `use_2to3` flag to setuptools resulted in `2to3` being run on the package _before_ building those bdists, resolving the problem in those specific releases (as I demonstrated in the last code block of my most recent comment).

Additionally, because python automatically adds the current working directory to `sys.path`, anyone who only ever does `python3 ./ciscoconfparse.py` or similar from the installed path will also never experience this issue.

> Please don't submit a PR at this point. I am not confident we know what is causing your problem.

What aspects of my steps to reproduce or the workaround involving installing a py3-specific bdist do you think are unclear or don't support my proposed root cause sufficiently?

**Comment by mpenning** [comment] 2019-05-12 13:19
Please try version 1.3.37

**Comment by roganartu** [comment] 2019-05-16 21:00
Confirming it appears to work. Thanks

```
╭─  ~ 
│
╰ python3 -m virtualenv -p $(which python3) env    
Running virtualenv with interpreter /home/tl/.pyenv/shims/python3
Using base prefix '/home/tl/.pyenv/versions/3.7.2'
New python executable in /home/tl/env/bin/python3
Also creating executable in /home/tl/env/bin/python
Installing setuptools, pip, wheel...
done.

╭─  ~ 
│
╰ . env/bin/activate

╭─  ~ 
│
╰ pip install ciscoconfparse==1.3.37
Collecting ciscoconfparse==1.3.37
  Downloading https://files.pythonhosted.org/packages/6b/f3/943e755dc7643c4c69bb4c41e5db4260d6472cea32af0fa18a562a786ab9/ciscoconfparse-1.3.37.tar.gz (94kB)
     |████████████████████████████████| 102kB 12.6MB/s 
Collecting colorama (from ciscoconfparse==1.3.37)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting passlib (from ciscoconfparse==1.3.37)
  Downloading https://files.pythonhosted.org/packages/ee/a7/d6d238d927df355d4e4e000670342ca4705a72f0bf694027cf67d9bcf5af/passlib-1.7.1-py2.py3-none-any.whl (498kB)
     |████████████████████████████████| 501kB 19.4MB/s 
Collecting dnspython (from ciscoconfparse==1.3.37)
  Downloading https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl (188kB)
     |████████████████████████████████| 194kB 20.6MB/s 
Building wheels for collected packages: ciscoconfparse
  Building wheel for ciscoconfparse (setup.py) ... done
  Stored in directory: /home/tl/.cache/pip/wheels/70/b7/2b/bfdc9d09620157c966b0e6e40a59d0b3c5b585009ad408b54b
Successfully built ciscoconfparse
Installing collected packages: colorama, passlib, dnspython, ciscoconfparse
Successfully installed ciscoconfparse-1.3.37 colorama-0.4.1 dnspython-1.16.0 passlib-1.7.1

╭─  ~ 
│
╰ python
Python 3.7.2 (default, Mar 18 2019, 19:08:32) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse import CiscoConfParse
>>> 

```
