### ISSUE TITLE
IPv6 Static Routes are Broken

### ISSUE THREAD

**Issue by MrRJ45** [mpenning/ciscoconfparse#34] opened 2015-04-14 13:36 UTC
After some head scratching I have found that when using factory=True the "_RE_IP_ROUTE" regex does not match IPv6. I get:

AttributeError: 'IOSRouteLine' object has no attribute 'route_info'

Because an (assumed) existing configuration file is being parsed then IOS should only allow valid entries and so I match both IPv4 and IPv6 myself with no validation.

Would this be the best way to fix this? If so I can modify the regex to cater for this.

**Comment by mpenning** [comment] 2015-04-14 13:59
Indeed, please remember that all 'factory=True' methods are beta right now.  I am working on IPv6 support but there is a lot to do.

**Comment by mpenning** [comment] 2015-04-17 11:22
Duplicate of Github issue #35

**Comment by mpenning** [comment] 2015-07-03 22:30
Apologies for the delay... This should be implemented now in models_cisco... please let me know if you run into issues or have unit tests to add.

**Closed by mpenning** 2015-07-03 22:30 UTC
Labels: duplicate, enhancement
